version: "3.9"

services:
  php:
    build: ./docker/php
    container_name: 'main_app_php'
    volumes:
      - .:/usr/src/app
    environment:
      PHP_IDE_CONFIG: "serverName=main_app_docker"
    networks:
      - main_app

  nginx:
    image: nginx:1.21.1
    container_name: 'main_app_nginx'
    ports:
      - '80:80'
    volumes:
      - .:/usr/src/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - main_app

networks:
  main_app:
